const plantData = [
  {
    id: 1,
    name: "Ugwu (Fluted Pumpkin)",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Rainy Season",
    soil: "Loamy, well-drained",
    growthRate: "Fast",
    description: "Popular leafy vegetable used in soups and stews across Nigeria.",
    image: "/catalogImg/fluted_pumpkin.jpg"
  },
  {
    id: 2,
    name: "Scent Leaf (Efirin)",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Rainy Season",
    soil: "Loamy, fertile",
    growthRate: "Fast",
    description: "Aromatic herb used in local dishes and traditional medicine.",
    image: "/catalogImg/scent_leaf.jpg"
  },
  {
    id: 3,
    name: "Okra",
    type: "plant",
    sun: "Full Sun",
    water: "High",
    season: "Rainy Season",
    soil: "Loamy, well-drained",
    growthRate: "Fast",
    description: "Fast-growing vegetable used in soups; thrives in warm climates.",
    image: "/catalogImg/Okra.jpg"
  },
  {
    id: 4,
    name: "Pepper (Ata Rodo)",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Year-Round (irrigated)",
    soil: "Sandy loam, well-drained",
    growthRate: "Medium",
    description: "Spicy pepper variety popular in Nigerian cooking.",
    image: "/catalogImg/pepper.jpg"
  },
  {
    id: 5,
    name: "Tomato",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Dry Season with irrigation",
    soil: "Loamy, well-drained",
    growthRate: "Fast",
    description: "Essential ingredient in stews and sauces.",
    image: "/catalogImg/tomato.jpg"
  },
  {
    id: 6,
    name: "Waterleaf (Gbure)",
    type: "plant",
    sun: "Partial Shade",
    water: "High",
    season: "Rainy Season",
    soil: "Moist, fertile",
    growthRate: "Fast",
    description: "Highly nutritious leafy green used in soups.",
    image: "/catalogImg/waterleaf.jpg"
  },
  {
    id: 7,
    name: "Amaranth (Green)",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Rainy Season",
    soil: "Loamy, well-drained",
    growthRate: "Fast",
    description: "Locally called 'Green'; grows fast and rich in iron.",
    image: "/catalogImg/amaranth.jpg"
  },
  {
    id: 8,
    name: "Bitter Leaf",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Rainy Season",
    soil: "Loamy, well-drained",
    growthRate: "Medium",
    description: "Used in traditional soups and herbal remedies.",
    image: "/catalogImg/bitterleaf.jpg"
  },
  {
    id: 9,
    name: "Telfairia occidentalis (Pumpkin)",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Rainy Season",
    soil: "Loamy, well-drained",
    growthRate: "Medium",
    description: "Climbing plant cultivated for its edible leaves and seeds.",
    image: "/catalogImg/pumpkin.jpg"
  },
  {
    id: 10,
    name: "Hibiscus (Zobo)",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Rainy Season",
    soil: "Loamy, well-drained",
    growthRate: "Medium",
    description: "Colorful flowering plant used ornamentally and for making hibiscus tea.",
    image: "/catalogImg/hibiscus.jpg"
  },
  {
    id: 11,
    name: "Bougainvillea",
    type: "plant",
    sun: "Full Sun",
    water: "Low",
    season: "Dry and Rainy",
    soil: "Sandy, well-drained",
    growthRate: "Fast",
    description: "Hardy tropical ornamental with vibrant bracts; ideal for fences and trellises.",
    image: "/catalogImg/bougainvillea.jpg"
  },
  {
    id: 12,
    name: "Lavender",
    type: "plant",
    sun: "Full Sun",
    water: "Low to Medium",
    season: "Dry Season",
    soil: "Sandy, well-drained",
    growthRate: "Slow",
    description: "Fragrant herb with calming properties; grows best in well-drained soil.",
    image: "/catalogImg/lavender.jpg"
  },
  {
    id: 13,
    name: "Ixora",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "All Seasons",
    soil: "Loamy, fertile",
    growthRate: "Medium",
    description: "Tropical shrub with clustered flowers; popular for hedging.",
    image: "/catalogImg/ixora.jpg"
  },
  {
    id: 14,
    name: "Marigold",
    type: "plant",
    sun: "Full Sun",
    water: "Low to Medium",
    season: "Dry and Rainy",
    soil: "Sandy, well-drained",
    growthRate: "Fast",
    description: "Bright, pest-repellent flower; used ornamentally and in traditional medicine.",
    image: "/catalogImg/marigold.jpg"
  },
  {
    id: 15,
    name: "Petunia",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Dry Season",
    soil: "Loamy, well-drained",
    growthRate: "Fast",
    description: "Colorful bedding plant ideal for pots and window boxes.",
    image: "/catalogImg/petunia.jpg"
  },
  {
    id: 16,
    name: "Lantana",
    type: "plant",
    sun: "Full Sun",
    water: "Low",
    season: "All Seasons",
    soil: "Sandy, well-drained",
    growthRate: "Fast",
    description: "Drought-tolerant flowering shrub with small clustered blooms.",
    image: "/catalogImg/lantana.jpg"
  },
  {
    id: 17,
    name: "Rose",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Dry and Rainy",
    soil: "Loamy, well-drained",
    growthRate: "Medium",
    description: "Classic fragrant flower; thrives in sunny, well-drained beds.",
    image: "/catalogImg/rose.jpg"
  },
  {
    id: 18,
    name: "Hydrangea",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Dry Season",
    soil: "Loamy, well-drained",
    growthRate: "Medium",
    description: "Fast-growing annuals with vibrant daisy-like flowers.",
    image: "/catalogImg/hydrangea.jpg"
  },
  {
    id: 19,
    name: "Allamanda",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Rainy Season",
    soil: "Loamy, well-drained",
    growthRate: "Fast",
    description: "Yellow-flowered vine commonly used in tropical gardens and fences.",
    image: "/catalogImg/allamanda.jpg"
  },
  {
    id: 20,
    name: "Croton",
    type: "plant",
    sun: "Partial Sun",
    water: "Medium",
    season: "All Seasons",
    soil: "Loamy, well-drained",
    growthRate: "Slow",
    description: "Tropical foliage plant with multicolored leaves; grown for visual appeal.",
    image: "/catalogImg/croton.jpg"
  },
  {
    id: 21,
    name: "African Lily (Agapanthus)",
    type: "plant",
    sun: "Full Sun",
    water: "Medium",
    season: "Dry and Rainy",
    soil: "Loamy, well-drained",
    growthRate: "Medium",
    description: "Graceful flowering plant with striking purple-blue blooms.",
    image: "/catalogImg/african_lily.jpg"
  }
];

export default plantData;
